apiVersion: autoscaling.gardener.cloud/v1alpha1
kind: PersistentVolumeClaimAutoscaler
metadata:
  name: my-pvca-2
  namespace: garden
spec:
  increaseBy: "10%"
  threshold: "20%"
  maxCapacity: 200Gi
  scaleTargetRef:
    name: vali-vali-0